import { describe, expect, it } from "vitest";
import { parseCareEvents, parseSingleCareEvent } from "@/src/domain/parser";

const context = { now: "2026-07-28T05:00:00.000Z", timeZone: "America/Los_Angeles", babyId: "baby-1" };
describe("deterministic care parser", () => {
  it("segments feed and diaper events with independent times", () => { const outcomes = parseCareEvents("Fed 3 oz at 8 pm then changed a wet diaper 10 minutes ago", context); expect(outcomes).toHaveLength(2); expect(outcomes[0]).toMatchObject({ outcome: "proposed", type: "feed", startedAt: "2026-07-28T03:00:00.000Z", fields: { mode: "bottle", volume: 3, unit: "oz" } }); expect(outcomes[1]).toMatchObject({ outcome: "proposed", type: "diaper", startedAt: "2026-07-28T04:50:00.000Z", fields: { kind: "wet" } }); });
  it("parses meridiem and bare 24-hour sleep intervals", () => { expect(parseSingleCareEvent("Slept from 9:30 pm to 11 pm", { ...context, now: "2026-07-28T07:30:00.000Z" })).toMatchObject({ outcome: "proposed", type: "sleep", startedAt: "2026-07-28T04:30:00.000Z", endedAt: "2026-07-28T06:00:00.000Z" }); expect(parseSingleCareEvent("Slept from 20:30 to 21:45", { ...context, now: "2026-07-28T07:30:00.000Z" })).toMatchObject({ outcome: "proposed", type: "sleep", startedAt: "2026-07-28T03:30:00.000Z", endedAt: "2026-07-28T04:45:00.000Z" }); });
  it("parses feeds with bare 24-hour clock notation", () => { expect(parseSingleCareEvent("Bottle-fed 90 ml 20:30", { ...context, now: "2026-07-28T07:30:00.000Z" })).toMatchObject({ outcome: "proposed", type: "feed", startedAt: "2026-07-28T03:30:00.000Z" }); });
  it("handles explicit calendar dates in the past", () => { expect(parseSingleCareEvent("Bottle-fed 90 ml on 2026-07-27 at 8 pm", context)).toMatchObject({ outcome: "proposed", startedAt: "2026-07-28T03:00:00.000Z" }); });
  it("refuses ambiguous, future, and DST-skipped clock phrases", () => { expect(parseSingleCareEvent("Fed at 3", context)).toMatchObject({ outcome: "refused", refusalReason: "ambiguous" }); expect(parseSingleCareEvent("Fed at 3:00", context)).toMatchObject({ outcome: "refused", refusalReason: "ambiguous" }); expect(parseSingleCareEvent("Fed tomorrow at 9 am", context)).toMatchObject({ outcome: "refused", refusalReason: "unsafe" }); expect(parseSingleCareEvent("Fed on 2026-03-08 at 2:30 am", { ...context, now: "2026-03-09T12:00:00.000Z" })).toMatchObject({ outcome: "refused", refusalReason: "ambiguous" }); });
  it("marks missing child and feed mode as unresolved instead of committing guesses", () => { const result = parseSingleCareEvent("Fed 5 minutes ago", { ...context, babyId: null }); expect(result).toMatchObject({ outcome: "proposed" }); if (result.outcome === "proposed") expect(result.unresolved).toEqual(expect.arrayContaining(["babyId", "fields.mode"])); });
  it("returns explicit empty and unsupported outcomes", () => { expect(parseSingleCareEvent("", context)).toMatchObject({ outcome: "refused", refusalReason: "empty" }); expect(parseSingleCareEvent("went for a walk", context)).toMatchObject({ outcome: "refused", refusalReason: "unsupported" }); });
});