import { describe, expect, it } from "vitest";
import { IanaTimeZoneSchema, durationMinutes, resolvePastTime, zonedDateTimeToInstant } from "@/src/domain/time";

describe("Temporal time utilities", () => {
  it("accepts IANA zones and rejects fixed offsets or invented zones", () => { expect(IanaTimeZoneSchema.safeParse("America/Los_Angeles").success).toBe(true); expect(IanaTimeZoneSchema.safeParse("Asia/Kolkata").success).toBe(true); expect(IanaTimeZoneSchema.safeParse("+05:30").success).toBe(false); expect(IanaTimeZoneSchema.safeParse("Mars/Olympus_Mons").success).toBe(false); });
  it("measures elapsed time across the Los Angeles fall-back", () => { const start = zonedDateTimeToInstant("2026-11-01", { hour: 0, minute: 30 }, "America/Los_Angeles"); const end = zonedDateTimeToInstant("2026-11-01", { hour: 1, minute: 30 }, "America/Los_Angeles", "later"); expect(durationMinutes(start, end)).toBe(120); });
  it("keeps Kolkata elapsed and wall duration aligned", () => { const start = zonedDateTimeToInstant("2026-07-28", { hour: 0 }, "Asia/Kolkata"); const end = zonedDateTimeToInstant("2026-07-28", { hour: 2 }, "Asia/Kolkata"); expect(durationMinutes(start, end)).toBe(120); });
  it("accounts for Lord Howe's 30-minute transition", () => { const start = zonedDateTimeToInstant("2026-10-04", { hour: 1, minute: 30 }, "Australia/Lord_Howe"); const end = zonedDateTimeToInstant("2026-10-04", { hour: 3 }, "Australia/Lord_Howe"); expect(durationMinutes(start, end)).toBe(60); });
  it("uses the nearest past clock occurrence and refuses explicit future dates", () => { const options = { now: "2026-07-28T05:00:00.000Z", timeZone: "America/Los_Angeles" }; const past = resolvePastTime("at 11 pm", options); expect(past.ok && past.instant).toBe("2026-07-27T06:00:00.000Z"); expect(resolvePastTime("2026-07-29 at 8 pm", options)).toMatchObject({ ok: false, reason: "future" }); });
  it("accepts bare two-digit 24-hour clocks but not ambiguous one-digit clocks", () => { const options = { now: "2026-07-28T07:30:00.000Z", timeZone: "America/Los_Angeles" }; expect(resolvePastTime("20:30", options)).toMatchObject({ ok: true, instant: "2026-07-28T03:30:00.000Z" }); expect(resolvePastTime("3:00", options)).toMatchObject({ ok: false, reason: "ambiguous" }); });
  it("refuses skipped or repeated DST wall times when no offset disambiguates them", () => { const options = { now: "2026-03-09T12:00:00.000Z", timeZone: "America/Los_Angeles" }; expect(resolvePastTime("2026-03-08 at 2:30 am", options)).toMatchObject({ ok: false, reason: "ambiguous" }); expect(resolvePastTime("2026-11-01 at 1:30 am", { ...options, now: "2026-11-02T12:00:00.000Z" })).toMatchObject({ ok: false, reason: "ambiguous" }); });
});