export const COPY = {
  meta: {
    title: "NuzzleCue — Care, captured and ready for handoff",
    description: "A private, device-local care record for calm capture, review, and caregiver handoff.",
  },
  global: {
    product: "NuzzleCue",
    codename: "Working codename",
    codenameDisclaimer: "NuzzleCue is a working codename, not a brand. No trademark claimed.",
    demo: "Demo family",
    live: "Live on this device",
    preview: "Preview",
    planned: "Planned",
    excluded: "Excluded",
    saved: "Saved on this device",
    close: "Close",
    back: "Back",
    continue: "Continue",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    undo: "Undo",
    done: "Done",
    skipToContent: "Skip to content",
    menu: "Menu",\n    closeGlyph: "×",\n    menuGlyph: "•••",
  },
  nav: {
    aria: "Primary navigation",
    today: "Today",
    capture: "Capture",
    timeline: "Timeline",
    insights: "Insights",
    handoff: "Handoff",
    privacy: "Privacy",
    settings: "Settings",
    status: "Feature status",
    demo: "Try demo",
    home: "Home",
  },
  home: {
    eyebrow: "A calmer care record",
    title: "Capture the care. Keep the handoff clear.",
    intro: "Log feeds, sleep, diapers, and everyday care with a sentence or a few taps. Review every detail before it joins the record.",
    primaryCta: "Set up on this device",
    secondaryCta: "Explore with a demo family",
    privacyNote: "Structured records stay in this browser. No account is created, and speech availability depends on your browser.",
    trustOneTitle: "Confirm before save",
    trustOneBody: "Typed or spoken entries become editable cards first. Nothing is added until you confirm it.",
    trustTwoTitle: "Built around the shift",
    trustTwoBody: "Open timers, recent care, and a factual briefing help the next caregiver pick up where you left off.",
    trustThreeTitle: "Local by design",
    trustThreeBody: "The launch experience has no family-data server. Your browser stores the record and gives you export and wipe controls.",
    flowEyebrow: "Made for full hands",
    flowTitle: "One calm path from moment to memory",
    flowSteps: [
      { number: "01", title: "Capture", body: "Type naturally, use quick logs, or choose push-to-talk when supported." },
      { number: "02", title: "Review", body: "Check timing, type, amounts, and any uncertain fields before saving." },
      { number: "03", title: "Hand off", body: "Build a concise shift brief and choose exactly when to share it." },
    ],
    disclosure: "This is a care log, not an emergency or safety-monitoring service.",\n    mockAvatar: "J",\n    mockTimer: "38:12",
  },
  onboarding: {
    eyebrow: "Set up in about a minute",
    title: "A care record that fits this household",
    intro: "These choices stay on this device and can be changed later.",
    step: "Step",
    of: "of",
    babyLabel: "What should the log call your little one?",
    babyPlaceholder: "Nickname or initial",
    timezoneLabel: "Care timezone",
    timezoneHelp: "Times are stored precisely and shown in this timezone.",
    localeLabel: "Date and time style",
    unitsLabel: "Bottle units",
    trackLabel: "What would you like in quick log?",
    tracking: ["Feeds", "Sleep", "Diapers", "Pumping", "Solids", "Tummy time"],
    privacyTitle: "Before the first entry",
    privacyBody: "Family data is kept by this browser. Browsers and operating systems can still clear local storage, so export a backup when it matters.",
    speechTitle: "Speech is always optional",
    speechBody: "Push-to-talk is only offered when your browser supports it. The browser or operating system may process speech away from this device; you will see this disclosure beside the control.",
    finish: "Open Today",
    localeUs: "Month / day / year",
    localeIntl: "Day / month / year",
    unitOz: "Fluid ounces",
    unitMl: "Milliliters",
    timezonePacific: "America / Los Angeles",
    timezoneEastern: "America / New York",
    timezoneLondon: "Europe / London",
    progressAria: "Onboarding progress",
  },
  today: {
    greeting: "Good morning",
    title: "Today with Juniper",
    subhead: "Monday, July 27 · Care day began at 7:00 AM",
    addEntry: "Add an entry",
    quickTitle: "Quick log",
    quickHint: "A few taps now, details can be edited later.",
    quickActions: [
      { key: "bottle", label: "Bottle", meta: "Choose amount" },
      { key: "nursing", label: "Nursing", meta: "Start a timer" },
      { key: "diaper", label: "Diaper", meta: "Wet, dirty, or both" },
      { key: "sleep", label: "Sleep", meta: "Start a timer" },
      { key: "tummy", label: "Tummy time", meta: "Log now" },
      { key: "solids", label: "Solids", meta: "Log now" },
    ],
    activeTitle: "Active now",
    activeCount: "1 timer",
    sleepTimer: "Sleep",
    sleepSince: "Started 9:42 AM",
    timerValue: "38 min",
    stopTimer: "Stop timer",
    recentTitle: "Recent care",
    viewTimeline: "View full timeline",
    events: [
      { time: "9:42 AM", title: "Sleep started", detail: "Timer is still running", tone: "sleep" },
      { time: "9:08 AM", title: "Wet diaper", detail: "Logged with quick entry", tone: "diaper" },
      { time: "8:24 AM", title: "Bottle · 3.5 fl oz", detail: "Formula · confirmed", tone: "feed" },
      { time: "7:36 AM", title: "Nursed · 18 min", detail: "Left and right", tone: "feed" },
    ],
    loggedPrefix: "Logged",
    logToast: "Entry saved to this in-memory preview.",
    timerStopped: "Sleep timer stopped at 38 minutes.",
    dayNote: "Care days use a 7:00 AM boundary, so late-night events stay with the shift that recorded them.",
  },
  capture: {
    eyebrow: "Capture",
    title: "What happened?",
    intro: "Use your own words. You will review an editable interpretation before anything is saved.",
    inputLabel: "Care note",
    placeholder: "For example: Juniper had 3 ounces at 8:20 and a wet diaper",
    parse: "Review this entry",
    mic: "Use push-to-talk",
    micUnavailable: "Speech unavailable? Typing and quick logs work the same way.",
    disclosureTitle: "Before using the microphone",
    disclosureBody: "Your browser or operating system may process speech away from this device. NuzzleCue does not store audio. Only the final transcript is used to build review cards.",
    disclosureAccept: "I understand, start listening",
    listening: "Listening…",
    listeningHint: "Try: “Bottle at 8:20, three ounces, then a wet diaper.”",
    stopListening: "Stop and review",
    reviewEyebrow: "Review before save",
    reviewTitle: "Check every detail",
    reviewIntro: "We separated your note into two proposed entries. Correct anything that is off.",
    original: "Original note",
    firstCard: "Bottle feed",
    secondCard: "Wet diaper",
    time: "Time",
    amount: "Amount",
    contents: "Contents",
    diaperType: "Type",
    assumed: "Assumed",
    assumedNow: "Time was not stated, so we assumed now.",
    confident: "Clear",
    uncertain: "Check this",
    formula: "Formula",
    wet: "Wet",
    save: "Confirm and save 2 entries",
    savedTitle: "Two entries saved",
    savedBody: "They are now part of this in-memory preview. Domain persistence will replace this seam during integration.",
    returnToday: "Return to Today",
    addAnother: "Capture another",
    emptyError: "Add a care note before continuing.",
    sampleTranscript: "Juniper had a 3 ounce bottle at 8:20 and a wet diaper after.",\n    reviewTimeOne: "8:20 AM",\n    reviewAmount: "3",\n    reviewTimeTwo: "8:26 AM",
  },
  timeline: {
    eyebrow: "Timeline",
    title: "The care record, in order",
    intro: "Filter without changing the underlying record.",
    filterAria: "Filter timeline",
    filters: ["All", "Feeds", "Sleep", "Diapers", "Other"],
    today: "Today",
    yesterday: "Yesterday",
    events: [
      { category: "Sleep", time: "9:42 AM–10:20 AM", title: "Sleep · 38 min", detail: "Ended by Anchit" },
      { category: "Diapers", time: "9:08 AM", title: "Wet diaper", detail: "Quick entry" },
      { category: "Feeds", time: "8:24 AM", title: "Bottle · 3.5 fl oz", detail: "Formula" },
      { category: "Feeds", time: "7:36 AM", title: "Nursed · 18 min", detail: "Left and right" },
      { category: "Other", time: "7:14 AM", title: "Tummy time · 6 min", detail: "Manual entry" },
      { category: "Sleep", time: "3:12–5:04 AM", title: "Sleep · 1 hr 52 min", detail: "Overnight" },
    ],
    olderEvents: [
      { category: "Diapers", time: "11:48 PM", title: "Wet + dirty diaper", detail: "Edited once" },
      { category: "Feeds", time: "11:17 PM", title: "Bottle · 3 fl oz", detail: "Expressed milk" },
    ],
    editEntry: "Edit entry",
    deleteEntry: "Delete entry",
    empty: "No entries match this filter.",
  },
  insights: {
    eyebrow: "Local insights",
    title: "Patterns, with their evidence",
    intro: "These descriptions use complete entries stored on this device. They do not assess wellbeing or tell you what to do.",
    formingTitle: "Patterns are still forming",
    formingBody: "Routine windows appear after 21 complete samples. There are 14 complete bottle entries right now.",
    evidence: "14 of 21 samples",
    sevenDay: "Past 7 care days",
    summaryCards: [
      { value: "7", label: "Bottle feeds", note: "Complete entries" },
      { value: "6 h 48 m", label: "Sleep logged", note: "Across 9 intervals" },
      { value: "8", label: "Diapers", note: "5 wet · 2 dirty · 1 both" },
    ],
    previewBadge: "Preview with demo evidence",
    previewTitle: "How a routine window will read",
    previewBody: "In the demo family’s last 28 complete entries, afternoon bottles began between 2:10 and 2:55 PM half the time.",
    sampleCount: "28 complete samples · refreshed today",
    rangeLabel: "Middle 50% of start times",
    rangeStart: "2:10",
    rangeEnd: "2:55",
    predictedTitle: "Possible next bottle window",
    predictedBody: "Based on the demo family’s recent intervals, the next recorded bottle may begin around 5:20–6:05 PM.",
    predictionCaveat: "A descriptive estimate from prior logs, not a reminder or care recommendation.",
    showEvidence: "Show evidence",
    hideEvidence: "Hide evidence",
    evidenceDetail: "Median interval: 2 h 51 m · middle 50%: 2 h 34 m–3 h 16 m · 25 complete intervals.",
  },
  handoff: {
    eyebrow: "Handoff",
    title: "Make the next shift easy to scan",
    intro: "Choose a boundary, check the facts, and share only when you are ready.",
    boundaryLabel: "Briefing starts",
    boundaryOptions: ["Last 4 hours", "Since 7:00 AM", "Since custom time"],
    briefTitle: "Shift briefing",
    editableHint: "The briefing is factual and editable before it is packaged.",
    summary: "Since 7:00 AM · 4 feeds · 3 diapers · 2 sleep intervals",
    openTitle: "Open item",
    openBody: "No active timers.",
    recentTitle: "Most recent",
    recentItems: [
      "10:20 AM · Sleep ended · 38 min",
      "9:08 AM · Wet diaper",
      "8:24 AM · Bottle · 3.5 fl oz formula",
      "7:36 AM · Nursed · 18 min",
    ],
    noteLabel: "Private edit for this briefing",
    notePlaceholder: "Keep this factual. Free text is not included in QR passes.",
    generate: "Prepare QR pass",
    warningTitle: "A shared copy leaves this device",
    warningBody: "The QR or link contains a compact copy of this briefing. Anyone with it can read the contents.",
    warningHistory: "If sent through text, email, or chat, a copy may remain in that app’s history.",
    warningExpiry: "The viewer stops opening it in this app after 12 hours. This is a courtesy limit, not revocation.",
    agree: "Prepare share options",
    qrTitle: "Handoff pass ready",
    qrAlt: "Decorative representation of a local handoff QR code",
    qrHint: "Scan with the next caregiver’s camera. The briefing data is inside the QR and is not uploaded by NuzzleCue.",
    expires: "Courtesy expiry · 11:18 PM today",
    copyLink: "Copy link instead",
    copied: "Link copied",
    rebuild: "Edit briefing",
    print: "Print briefing",
    size: "Pass size · 684 of 1,200 bytes",
  },
  privacy: {
    eyebrow: "Privacy center",
    title: "Your browser, your controls",
    intro: "This launch keeps structured family records in this browser. There is no NuzzleCue account or family-data server.",
    storageTitle: "Device storage",
    storageBody: "About 184 KB used for this family. Persistent storage is not yet confirmed.",
    storageAction: "Request persistent storage",
    storageConfirmed: "Persistent storage requested",
    backupTitle: "Take a backup",
    backupBody: "Export a portable JSON backup or a CSV ZIP with a provenance notice.",
    exportJson: "Export JSON",
    exportCsv: "Export CSV ZIP",
    exportMetrics: "Export local usage metrics",
    importTitle: "Restore a backup",
    importBody: "Imports are checked before they can replace or add to the record.",
    chooseFile: "Choose JSON backup",
    sharingTitle: "Sharing boundaries",
    sharingBody: "Handoff passes are deliberate copies. Courtesy expiry cannot remove screenshots, downloads, or messages.",
    deleteTitle: "Delete everything",
    deleteBody: "Clears real-family records, preferences, and app caches in the integrated build. The demo family remains separate.",
    deleteAction: "Begin delete",
    confirmLabel: "Type DELETE to confirm",
    confirmWord: "DELETE",
    deleteForever: "Delete this device’s family data",
    deleted: "This in-memory preview has been cleared.",
    exportDone: "A sample local export was prepared.",
    provenance: "Self-reported, unverified, generated locally, not a clinical record.",
  },
  settings: {
    eyebrow: "Settings",
    title: "Make the log feel at home",
    intro: "Preferences apply only in this browser.",
    appearanceTitle: "Appearance",
    nurseryTheme: "Nursery theme",
    nurseryBody: "Warmer colors and softer surfaces, with the same contrast targets.",
    motion: "Reduce motion",
    motionBody: "Also follows your operating system preference.",
    profileTitle: "Care profile",
    nickname: "Nickname",
    timezone: "Timezone",
    units: "Bottle units",
    dayBoundary: "Care day boundary",
    boundaryValue: "7:00 AM",\n    nicknameValue: "Juniper",
    save: "Save preferences",
    saved: "Preferences saved in this preview.",
    installTitle: "Install this app",
    installBody: "Use your browser’s Add to Home Screen or Install command. Availability varies by browser.",
    installHelp: "Show install help",
    collaborationTitle: "Caregiver collaboration",
    collaborationBody: "Accounts, live sync, and caregiver roles need a separately reviewed encrypted architecture.",
    notificationsTitle: "Reminders and widgets",
    notificationsBody: "User-scheduled push, native widgets, and system shortcuts are not part of this web launch.",
  },
  status: {
    eyebrow: "Feature status",
    title: "What works, what is a demo, and what is not promised",
    intro: "Every surface is labeled so a preview never masquerades as a live capability.",
    liveTitle: "Live on this device",
    liveBody: "Designed to use a real local record after domain integration.",
    liveItems: ["Capture and explicit review", "Today, timers, and timeline", "Local summaries and handoff", "Export, import, and delete controls"],
    demoTitle: "Demo and preview",
    demoBody: "Interactive behavior using only a synthetic family.",
    demoItems: ["Sample family", "Evidence-rich routine window", "Professional roster research"],
    plannedTitle: "Planned, not available",
    plannedItems: [
      { title: "Encrypted multi-device sync", body: "Needs accounts, server design, and key recovery decisions." },
      { title: "Caregiver invitations and roles", body: "Depends on the collaboration architecture." },
      { title: "Reminders, widgets, and shortcuts", body: "Needs platform-specific delivery and permission design." },
    ],
    excludedTitle: "Intentionally excluded",
    excludedItems: [
      { title: "Emergency and safety monitoring", body: "A care log must not create false reassurance." },
      { title: "Clinical interpretation or care instructions", body: "The product records and summarizes only what people enter." },
      { title: "Always-on listening or baby-monitor media", body: "Background audio and video collection are outside the product boundary." },
      { title: "Advertising or data brokerage", body: "Family records are not an ad product." },
    ],
  },
  demo: {
    banner: "You are exploring an isolated synthetic family. Nothing here enters your real-family record.",
    switch: "Leave demo",
    family: "The Rivera demo family",
    title: "Today with Mira",
    subhead: "Synthetic care day · Monday, July 27",
  },
  pass: {
    eyebrow: "Read-only handoff pass",
    title: "Mira’s shift briefing",
    source: "Demo data",
    sourceBody: "This pass contains synthetic sample data.",
    generated: "Prepared at 11:18 AM · courtesy expiry at 11:18 PM",
    expiredTitle: "About expiry",
    expiredBody: "Expiry is an app courtesy. It cannot remove a saved link, screenshot, printout, or message history.",
    summary: "Since 7:00 AM · 4 feeds · 3 diapers · 2 sleep intervals",
    open: "Open items",
    none: "No active timers.",
    recents: "Most recent care",
    provenance: "Self-reported, unverified, generated locally, not a clinical record.",
    invalidTitle: "This pass cannot be opened",
    invalidBody: "It may be incomplete, changed, or past its courtesy expiry.",
  },
} as const;

export type ExperiencePage =
  | "home"
  | "onboarding"
  | "today"
  | "capture"
  | "timeline"
  | "insights"
  | "handoff"
  | "privacy"
  | "settings"
  | "status"
  | "demo"
  | "pass";
