const SAMPLE_CLOCK_LABELS = Object.freeze({
  sleepStart: "9:42 AM",
  sleepEnd: "10:20 AM",
});

export const COPY = {
  meta: {
    title: "NuzzleCue — Care, captured and ready for handoff",
    description: "A private, device-local care record for calm capture, review, and caregiver handoff.",
  },
  global: {
    product: "NuzzleCue",
    codename: "Working codename",
    codenameDisclaimer: "NuzzleCue is a working codename, not a brand. No trademark claimed.",
    demo: "Demo family",
    live: "Live on this device",
    preview: "Preview",
    planned: "Planned",
    excluded: "Excluded",
    saved: "In-memory preview updated",
    close: "Close",
    back: "Back",
    continue: "Continue",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    undo: "Undo",
    done: "Done",
    skipToContent: "Skip to content",
    menu: "Menu",
    closeGlyph: "×",
    menuGlyph: "•••",
    menuPlanned: "Event actions — planned after repository integration",
    editPlanned: "Edit action — planned after repository integration",
    deletePlanned: "Delete action — planned after repository integration",
  },
  nav: {
    aria: "Navigation",
    publicAria: "Public navigation",
    primaryAria: "Care navigation",
    secondaryAria: "Privacy and settings navigation",
    mobileAria: "Mobile care navigation",
    today: "Today",
    capture: "Capture",
    timeline: "Timeline",
    insights: "Insights",
    handoff: "Handoff",
    privacy: "Privacy",
    settings: "Settings",
    status: "Feature status",
    demo: "Try demo",
    home: "Home",
  },
  home: {
    eyebrow: "A calmer care record",
    title: "Capture the care. Keep the handoff clear.",
    intro: "Log feeds, sleep, diapers, and everyday care with a sentence or a few taps. Review every detail before it joins the record.",
    primaryCta: "Set up on this device",
    secondaryCta: "Explore with a demo family",
    privacyNote: "Structured records stay in this browser. No account is created, and speech availability depends on your browser.",
    trustOneTitle: "Confirm before save",
    trustOneBody: "Typed or spoken entries become editable cards first. Nothing is added until you confirm it.",
    trustTwoTitle: "Built around the shift",
    trustTwoBody: "Open timers, recent care, and a factual briefing help the next caregiver pick up where you left off.",
    trustThreeTitle: "Local by design",
    trustThreeBody: "The launch experience has no family-data server. Your browser stores the record and gives you export and wipe controls.",
    flowEyebrow: "Made for full hands",
    flowTitle: "One calm path from moment to memory",
    flowSteps: [
      { number: "01", title: "Capture", body: "Type naturally, use quick logs, or choose push-to-talk when supported." },
      { number: "02", title: "Review", body: "Check timing, type, amounts, and any uncertain fields before saving." },
      { number: "03", title: "Hand off", body: "Build a concise shift brief and choose exactly when to share it." },
    ],
    disclosure: "This is a care log, not an emergency or safety-monitoring service.",
    samplePreview: "Sample preview",
    samplePreviewAlt: "Illustrative sample care card with a sample timer and two sample events.",
    mockAvatar: "J",
    mockTimer: "38:12",
  },
  onboarding: {
    eyebrow: "Set up in about a minute",
    title: "A care record that fits this household",
    intro: "These choices stay on this device and can be changed later.",
    step: "Step",
    of: "of",
    totalSteps: "3",
    babyLabel: "What should the log call your little one?",
    babyPlaceholder: "Nickname or initial",
    timezoneLabel: "Care timezone",
    timezoneHelp: "Times are stored precisely and shown in this timezone.",
    localeLabel: "Date and time style",
    unitsLabel: "Bottle units",
    trackLabel: "What would you like in quick log?",
    tracking: ["Feeds", "Sleep", "Diapers", "Pumping", "Solids", "Tummy time"],
    privacyTitle: "Before the first entry",
    privacyBody: "Family data is kept by this browser. Browsers and operating systems can still clear local storage, so export a backup when it matters.",
    speechTitle: "Speech is always optional",
    speechBody: "Push-to-talk is only offered when your browser supports it. The browser or operating system may process speech away from this device; you will see this disclosure beside the control.",
    finish: "Open Today",
    localeUs: "Month / day / year",
    localeIntl: "Day / month / year",
    unitOz: "Fluid ounces",
    unitMl: "Milliliters",
    timezonePacific: "America / Los Angeles",
    timezoneEastern: "America / New York",
    timezoneLondon: "Europe / London",
    progressAria: "Onboarding progress",
    previewDisclosure: "Preview: setup choices remain in memory for this visit and are not yet written to a device repository.",
  },
  today: {
    greeting: "Good morning",
    title: "Today with Juniper",
    subhead: "Illustrative sample day · Monday, July 27",
    sampleDisclosure: "Preview: the events, counts, and timer below are illustrative sample data, not records found on this device.",
    addEntry: "Add an entry",
    quickTitle: "Quick log",
    quickHint: "A few taps now, details can be edited later.",
    quickActions: [
      { key: "bottle", label: "Bottle", meta: "Choose amount" },
      { key: "nursing", label: "Nursing", meta: "Start a timer" },
      { key: "diaper", label: "Diaper", meta: "Wet, dirty, or both" },
      { key: "sleep", label: "Sleep", meta: "Start a timer" },
      { key: "tummy", label: "Tummy time", meta: "Log now" },
      { key: "solids", label: "Solids", meta: "Log now" },
    ],
    activeTitle: "Active now",
    activeCount: "1 sample timer",
    sleepTimer: "Sleep",
    sleepSince: `Sample start · ${SAMPLE_CLOCK_LABELS.sleepStart}`,
    timerValue: "38 min",
    stopTimer: "Stop timer",
    recentTitle: "Sample recent care",
    viewTimeline: "View full timeline",
    events: [
      { time: SAMPLE_CLOCK_LABELS.sleepStart, title: "Sleep started", detail: "Timer is still running", tone: "sleep" },
      { time: "9:08 AM", title: "Wet diaper", detail: "Logged with quick entry", tone: "diaper" },
      { time: "8:24 AM", title: "Bottle · 3.5 fl oz", detail: "Formula · confirmed", tone: "feed" },
      { time: "7:36 AM", title: "Nursed · 18 min", detail: "Left and right", tone: "feed" },
    ],
    loggedPrefix: "Logged",
    logToast: "Entry saved to this in-memory preview.",
    timerStopped: "Sample sleep timer stopped at 38 minutes.",
    dayNote: "Care days use a 7:00 AM boundary, so late-night events stay with the shift that recorded them.",
  },
  capture: {
    eyebrow: "Capture",
    title: "What happened?",
    intro: "Use your own words. You will review an editable interpretation before anything is saved.",
    inputLabel: "Care note",
    placeholder: "For example: Juniper had 3 ounces at 8:20 and a wet diaper",
    parse: "Review this entry",
    mic: "Preview push-to-talk flow",
    micUnavailable: "Speech unavailable? Typing and quick logs work the same way.",
    disclosureTitle: "Before using the microphone",
    disclosureBody: "This interaction preview does not access the microphone. In the integrated flow, your browser or operating system may process speech away from this device; NuzzleCue will not store audio.",
    disclosureAccept: "I understand, start listening",
    listening: "Listening-state preview",
    listeningHint: "Try: “Bottle at 8:20, three ounces, then a wet diaper.”",
    stopListening: "Stop and review",
    reviewEyebrow: "Review before save",
    reviewTitle: "Check every detail",
    reviewIntro: "This interaction preview shows two illustrative proposed entries. It is not connected to the parser yet.",
    reviewPreview: "Parser preview · sample interpretation",
    original: "Original note",
    firstCard: "Bottle feed",
    secondCard: "Wet diaper",
    time: "Time",
    amount: "Amount",
    contents: "Contents",
    diaperType: "Type",
    assumed: "Assumed",
    assumedNow: "Time was not stated, so we assumed now.",
    confident: "Clear",
    uncertain: "Check this",
    formula: "Formula",
    wet: "Wet",
    save: "Confirm 2 preview entries",
    savedTitle: "Two preview entries confirmed",
    savedBody: "They exist only in this in-memory interaction preview. No device record or backup was changed.",
    returnToday: "Return to Today",
    addAnother: "Capture another",
    emptyError: "Add a care note before continuing.",
    sampleTranscript: "Juniper had a 3 ounce bottle at 8:20 and a wet diaper after.",
    reviewTimeOne: "8:20 AM",
    reviewAmount: "3",
    reviewTimeTwo: "8:26 AM",
  },
  timeline: {
    eyebrow: "Timeline",
    title: "The care record, in order",
    intro: "Explore filtering without changing a device record.",
    sampleDisclosure: "Preview: every timeline entry shown here is illustrative sample data.",
    filterAria: "Filter timeline",
    filters: ["All", "Feeds", "Sleep", "Diapers", "Other"],
    today: "Sample care day",
    yesterday: "Earlier sample day",
    events: [
      { category: "Sleep", time: `${SAMPLE_CLOCK_LABELS.sleepStart}–${SAMPLE_CLOCK_LABELS.sleepEnd}`, title: "Sleep · 38 min", detail: "Ended by Anchit" },
      { category: "Diapers", time: "9:08 AM", title: "Wet diaper", detail: "Quick entry" },
      { category: "Feeds", time: "8:24 AM", title: "Bottle · 3.5 fl oz", detail: "Formula" },
      { category: "Feeds", time: "7:36 AM", title: "Nursed · 18 min", detail: "Left and right" },
      { category: "Other", time: "7:14 AM", title: "Tummy time · 6 min", detail: "Manual entry" },
      { category: "Sleep", time: "3:12–5:04 AM", title: "Sleep · 1 hr 52 min", detail: "Overnight" },
    ],
    olderEvents: [
      { category: "Diapers", time: "11:48 PM", title: "Wet + dirty diaper", detail: "Edited once" },
      { category: "Feeds", time: "11:17 PM", title: "Bottle · 3 fl oz", detail: "Expressed milk" },
    ],
    editEntry: "Edit entry — planned after repository integration",
    deleteEntry: "Delete entry — planned after repository integration",
    empty: "No entries match this filter.",
  },
  insights: {
    eyebrow: "Local insights",
    title: "Patterns, with their evidence",
    intro: "This preview demonstrates evidence language with synthetic samples. It does not read this device’s record or tell you what to do.",
    sampleDisclosure: "Preview: all counts, intervals, and routine windows on this page are synthetic sample data.",
    formingTitle: "Patterns are still forming",
    formingBody: "The sample dataset has 14 complete bottle entries. An integrated routine window will require 21 real complete samples.",
    evidence: "Sample evidence · 14 of 21",
    sevenDay: "Sample 7-day summary",
    summaryCards: [
      { value: "7", label: "Bottle feeds", note: "Complete entries" },
      { value: "6 h 48 m", label: "Sleep logged", note: "Across 9 intervals" },
      { value: "8", label: "Diapers", note: "5 wet · 2 dirty · 1 both" },
    ],
    previewBadge: "Preview with demo evidence",
    previewTitle: "How a routine window will read",
    previewBody: "In the demo family’s last 28 complete entries, afternoon bottles began between 2:10 and 2:55 PM half the time.",
    sampleCount: "28 complete samples · refreshed today",
    rangeLabel: "Middle 50% of start times",
    rangeStart: "2:10",
    rangeEnd: "2:55",
    predictedTitle: "Possible next bottle window",
    predictedBody: "Based on the demo family’s recent intervals, the next recorded bottle may begin around 5:20–6:05 PM.",
    predictionCaveat: "A descriptive estimate from prior logs, not a reminder or care recommendation.",
    showEvidence: "Show evidence",
    hideEvidence: "Hide evidence",
    evidenceDetail: "Median interval: 2 h 51 m · middle 50%: 2 h 34 m–3 h 16 m · 25 complete intervals.",
  },
  handoff: {
    eyebrow: "Handoff",
    title: "Make the next shift easy to read",
    intro: "Preview the factual shape of a shift brief before domain and sharing integration.",
    sampleDisclosure: "Preview: every briefing fact, event, count, time, and share control below uses synthetic sample data.",
    boundaryLabel: "Briefing starts",
    boundaryOptions: ["Last 4 hours", "Since 7:00 AM", "Since custom time"],
    briefTitle: "Shift briefing",
    editableHint: "The briefing is factual and editable before it is packaged.",
    summary: "Sample since 7:00 AM · 4 feeds · 3 diapers · 2 sleep intervals",
    openTitle: "Open item",
    openBody: "No active timers.",
    recentTitle: "Most recent",
    recentItems: [
      "10:20 AM · Sleep ended · 38 min",
      "9:08 AM · Wet diaper",
      "8:24 AM · Bottle · 3.5 fl oz formula",
      "7:36 AM · Nursed · 18 min",
    ],
    noteLabel: "Private edit for this briefing",
    notePlaceholder: "Keep this factual. Free text is not included in QR passes.",
    generate: "Preview handoff sharing",
    warningTitle: "How integrated sharing will work",
    warningBody: "No pass is generated in this preview. After codec integration, a deliberate QR or link action will create a copy that anyone holding it can read.",
    warningHistory: "If sent through text, email, or chat, a copy may remain in that app’s history.",
    warningExpiry: "The viewer stops opening it in this app after 12 hours. This is a courtesy limit, not revocation.",
    agree: "Open visual placeholder",
    qrTitle: "Share-card layout preview",
    qrAlt: "Decorative, non-scannable placeholder tile with no encoded data",
    qrHint: "Visual placeholder only. It cannot be scanned and contains no briefing or family data.",
    expires: "A real pass would show a 12-hour courtesy expiry",
    copyLink: "Copy sample placeholder link",
    copied: "Sample placeholder link copied · no briefing data included",
    copyUnavailable: "Clipboard unavailable · no data was shared",
    rebuild: "Edit briefing",
    print: "Print — planned",
    size: "Visual placeholder · no payload encoded",
  },
  privacy: {
    eyebrow: "Privacy center",
    title: "Your browser, your controls",
    intro: "This launch keeps structured family records in this browser. There is no NuzzleCue account or family-data server.",
    storageTitle: "Device storage",
    storageBody: "Storage usage will appear after repository integration. You can still ask this browser to make future local storage less likely to be cleared.",
    storageAction: "Request persistent storage",
    storageRequesting: "Requesting…",
    storageGranted: "Persistent storage granted by this browser",
    storageDenied: "This browser did not grant persistent storage",
    storageUnavailable: "Persistent storage requests are unavailable here",
    backupTitle: "Take a backup",
    backupBody: "Backup generation is planned for domain integration. Disabled controls below do not create files.",
    exportJson: "JSON backup — planned",
    exportCsv: "CSV ZIP export — planned",
    exportMetrics: "Metrics export — planned",
    importTitle: "Restore a backup",
    importBody: "Validated restore is planned for repository integration. This preview cannot read a backup.",
    chooseFile: "Choose JSON backup — planned",
    sharingTitle: "Sharing boundaries",
    sharingBody: "Handoff passes are deliberate copies. Courtesy expiry cannot remove screenshots, downloads, or messages.",
    deleteTitle: "Delete everything",
    deleteBody: "Repository and cache deletion will be enabled after domain integration. This disabled preview cannot remove device data.",
    deleteAction: "Delete-all — planned",
    confirmLabel: "Type DELETE to confirm",
    confirmWord: "DELETE",
    deleteForever: "Delete this device’s family data — planned",
    deleted: "No device data was changed.",
    exportDone: "No preview export is created.",
    provenance: "Self-reported, unverified, generated locally, not a clinical record.",
  },
  settings: {
    eyebrow: "Settings",
    title: "Make the log feel at home",
    intro: "Appearance preferences are stored in this browser. Care-profile fields remain an in-memory preview.",
    appearanceTitle: "Appearance",
    appearanceSaved: "Appearance settings are preserved in this browser.",
    nurseryTheme: "Nursery theme",
    nurseryBody: "Warmer colors and softer surfaces, with the same contrast targets.",
    motion: "Reduce motion",
    motionBody: "Also follows your operating system preference.",
    profileTitle: "Care profile",
    profilePreview: "Preview: profile changes are not connected to the device repository yet.",
    nickname: "Nickname",
    timezone: "Timezone",
    units: "Bottle units",
    dayBoundary: "Care day boundary",
    boundaryValue: "7:00 AM",
    nicknameValue: "Juniper",
    save: "Save preferences",
    saved: "Care-profile changes are held only in this in-memory preview.",
    installTitle: "Install this app",
    installBody: "Use your browser’s Add to Home Screen or Install command. Availability varies by browser.",
    installHelp: "Install walkthrough — planned",
    collaborationTitle: "Caregiver collaboration",
    collaborationBody: "Accounts, live sync, and caregiver roles need a separately reviewed encrypted architecture.",
    notificationsTitle: "Reminders and widgets",
    notificationsBody: "User-scheduled push, native widgets, and system shortcuts are not part of this web launch.",
  },
  live: {
    previewController: "Preview controller · sample state only",
    working: "Working…",
    saved: "Saved on this device.",
    actionError: "That action did not finish. Try again.",
    pending: "Please wait",
    closeDialog: "Close dialog",
    todayDate: "Care day",
    quickReviewTitle: "Review quick log",
    quickReviewBody: "Confirm this quick entry before adding it to the care record.",
    quickConfirm: "Confirm quick log",
    timerStart: "Start timer",
    timerStop: "Stop timer",
    timerNoActive: "No timers are active.",
    undoLast: "Undo last change",
    onboardingSaving: "Saving setup…",
    onboardingComplete: "Setup saved.",
    speechProbe: "Check speech availability",
    speechAccept: "I understand and want to continue",
    speechReady: "Speech is ready when you are.",
    speechPermission: "Waiting for microphone permission…",
    speechDenied: "Microphone permission was refused. Typing remains available.",
    speechUnavailable: "Speech is unavailable here. Typing remains available.",
    speechCancel: "Cancel speech",
    parseRefused: "Could not turn this part into an entry",
    unresolved: "Needs review",
    originalNote: "Source note",
    confirmEntries: "Confirm reviewed entries",
    committing: "Saving reviewed entries…",
    committedTitle: "Entry saved",
    committedBody: "The reviewed entries were added to this device’s care record.",
    captureAgain: "Capture another entry",
    retry: "Try again",
    reset: "Start over",
    timelineEdit: "Edit care entry",
    timelineDeleteTitle: "Delete this care entry?",
    timelineDeleteBody: "The entry will leave the visible care record. You can undo immediately afterward.",
    timelineDeleteConfirm: "Delete entry",
    timelineSave: "Save changes",
    noTimelineEntries: "No entries match this filter.",
    allFilter: "All",
    evidenceTitle: "Evidence",
    staleEvidence: "Evidence may be stale",
    formingProgress: "Evidence progress",
    generated: "Generated",
    handoffConsentTitle: "Create a shareable copy?",
    handoffConsentBody: "Anyone holding the QR code or link can read its contents. Courtesy expiry cannot revoke screenshots or message history.",
    handoffQr: "Create QR pass",
    handoffUrl: "Create link pass",
    handoffPreparing: "Preparing handoff…",
    handoffTooLarge: "This briefing is too large for the selected sharing method.",
    handoffError: "The handoff could not be created.",
    encodedQr: "Scannable handoff QR code",
    copyReadyLink: "Copy handoff link",
    rebuildHandoff: "Rebuild briefing",
    passEmptyTitle: "No handoff pass found",
    passEmptyBody: "Open the complete link or scan the original QR code.",
    passInvalidBody: "This pass is incomplete or changed.",
    passExpiredBody: "This pass is past its courtesy expiry, so its care details are hidden.",
    passSummary: "Shift summary",
    passEvents: "Included care events",
    storageGranted: "Persistent storage is enabled.",
    importPreviewTitle: "Review backup before import",
    importConfirm: "Import reviewed backup",
    importReading: "Reading backup…",
    importSuccess: "Backup imported.",
    importWarnings: "Import warnings",
    deleteTitle: "Permanently delete this device’s family data?",
    deleteBody: "This removes the care record, settings, backups cached by the app, and demo reset state from this browser.",
    deleteInstruction: "Type DELETE to confirm.",
    deleteForever: "Delete everything",
    exportJson: "Export JSON",
    exportCsv: "Export CSV ZIP",
    exportMetrics: "Export metrics JSON",
    chooseBackup: "Choose JSON backup",
    settingsHydrated: "Loaded from this device.",
    settingsSaved: "Settings saved.",
    demoReset: "Reset demo family",
    demoResetDone: "Demo family reset.",
    demoRealm: "Demo realm",
    realRealm: "Real family",
    leaveDemo: "Leave demo without entering the real care record",
  },
  status: {
    eyebrow: "Feature status",
    title: "What works, what is a demo, and what is not promised",
    intro: "Every surface is labeled so a preview never masquerades as a live capability.",
    liveTitle: "Live on this device",
    liveBody: "Designed to use a real local record after domain integration.",
    liveItems: ["Capture and explicit review", "Today, timers, and timeline", "Local summaries and handoff", "Export, import, and delete controls"],
    demoTitle: "Demo and preview",
    demoBody: "Interactive behavior using only a synthetic family.",
    demoItems: ["Sample family", "Evidence-rich routine window", "Professional roster research"],
    plannedTitle: "Planned, not available",
    plannedItems: [
      { title: "Encrypted multi-device sync", body: "Needs accounts, server design, and key recovery decisions." },
      { title: "Caregiver invitations and roles", body: "Depends on the collaboration architecture." },
      { title: "Reminders, widgets, and shortcuts", body: "Needs platform-specific delivery and permission design." },
    ],
    excludedTitle: "Intentionally excluded",
    excludedItems: [
      { title: "Emergency and safety monitoring", body: "A care log must not create false reassurance." },
      { title: "Clinical interpretation or care instructions", body: "The product records and summarizes only what people enter." },
      { title: "Always-on listening or baby-monitor media", body: "Background audio and video collection are outside the product boundary." },
      { title: "Advertising or data brokerage", body: "Family records are not an ad product." },
    ],
  },
  demo: {
    banner: "You are exploring an isolated synthetic family. Nothing here enters your real-family record.",
    switch: "Leave demo",
    family: "The Rivera demo family",
    title: "Today with Mira",
    subhead: "Synthetic care day · Monday, July 27",
  },
  pass: {
    eyebrow: "Read-only handoff pass",
    title: "Mira’s shift briefing",
    source: "Demo data",
    sourceBody: "This pass contains synthetic sample data.",
    generated: "Synthetic sample · example generation time with a 12-hour courtesy-expiry window",
    expiredTitle: "About expiry",
    expiredBody: "Expiry is an app courtesy. It cannot remove a saved link, screenshot, printout, or message history.",
    summary: "Synthetic sample since 7:00 AM · 4 feeds · 3 diapers · 2 sleep intervals",
    open: "Open items",
    none: "No active timers.",
    recents: "Most recent care",
    provenance: "Self-reported, unverified, generated locally, not a clinical record.",
    invalidTitle: "This pass cannot be opened",
    invalidBody: "It may be incomplete or changed. Try the original handoff source.",
    expiredStateTitle: "This sample pass is past its courtesy expiry",
    expiredStateBody: "The viewer hides expired content as a courtesy. This cannot remove screenshots, saved links, printouts, or message history.",
  },
} as const;

export type ExperiencePage =
  | "home"
  | "onboarding"
  | "today"
  | "capture"
  | "timeline"
  | "insights"
  | "handoff"
  | "privacy"
  | "settings"
  | "status"
  | "demo"
  | "pass";
